### ISSUE TITLE
Queries for disabled host wifi network

### ISSUE THREAD

**Issue by mundschenk-at** [home-assistant/plugin-dns#110]
I've noticed periodic log entries for queries for the (disabled) `wlan0` in the DNS plugin logs on my Home Assistant Yellow. Where are those coming from?

```
[INFO] 172.30.32.1:42640 - 36490 "A IN wlan0.local.hass.io. udp 37 false 512" NXDOMAIN qr,aa,rd 37 0.000673009s
[INFO] 172.30.32.1:38334 - 21566 "A IN wlan0.local.hass.io. udp 37 false 512" NXDOMAIN qr,aa,rd 37 0.000453124s
[INFO] 172.30.32.1:36936 - 42800 "A IN wlan0.local.hass.io. udp 37 false 512" NXDOMAIN qr,aa,rd 37 0.00075197s
[INFO] 172.30.32.1:36071 - 29497 "A IN wlan0.local.hass.io. udp 37 false 512" NXDOMAIN qr,aa,rd 37 0.000413456s
```

**Comment by codyc1515** [comment]
I am also seeing this. I believe it happens every time you visit this page: http://homeassistant.local:8123/config/network

**Comment by ThisWayToo** [comment]
I have encountered seeing this too on RPi 4 with the WLAN disabled. OS 15.0 and HA Core 2025.3.4.

I was able to resolve it for now by a OS reboot.

Upon reboot I went back into the network settings to see if that triggers it. Does not seem to here.
