### ISSUE TITLE
DNS plugin doesn’t support IPv6

### ISSUE THREAD

**Issue by Kars-de-Jong** [home-assistant/plugin-dns#7]
**Home Assistant release with the issue:**

0.116.4

**Operating environment (HassOS/Generic):**

HassOS 4.13 - ova - kvm

**Supervisor logs:**

20-10-16 07:58:00 WARNING (MainThread) [supervisor.plugins.dns] Ignore invalid DNS Server: dns://2001:b88:1002::10
20-10-16 07:58:00 WARNING (MainThread) [supervisor.plugins.dns] Ignore invalid DNS Server: dns://2001:b88:1202::10
20-10-16 07:58:00 WARNING (MainThread) [supervisor.plugins.dns] Ignore invalid DNS Server: dns://2001:730:3e42:1000::53

**Description of problem:**
The dns plugin doesn’t seem to support IPv6 DNS servers.

**Comment by pvizeli** [comment]
See https://github.com/home-assistant/supervisor/issues/2133

**Comment by Kars-de-Jong** [comment]
@frenck are you sure this issue belongs in this repo? It's the Python code that seems to have a problem (as in it expects IPv4 addresses).

**Comment by pvizeli** [comment]
do you read the RFC?

**Comment by Kars-de-Jong** [comment]
Yes, I did, I understand that having IPv6 support in Docker is "complicated", and actually putting IPv6 address in the list of DNS servers doesn't actually make much sense now.

I still don't think that is related to this issue though... it's more the fact that the supervisor dns plugin [this line](https://github.com/home-assistant/supervisor/blob/7a9aac491e3e0072ad788c836caa478e7e38fdd3/supervisor/plugins/dns.py#L293) of the logs that it is an **invalid** server. It's not invalid, it's just not currently meaningful inside a Docker container.

**Comment by pvizeli** [comment]
Do you think that a container without an IPv6 address can communicate over IPv6?

**Comment by Kars-de-Jong** [comment]
No, I don't think it will. But even if you implement it, the Python code still needs to be fixed. And the Python code lives in a different repository.
The best way to fix this (for now) the way I see it is to:
* Log actually invalid DNS server addresses the way it is currently done.
* Generate a debug level log message such as "IPv6 DNS server xxx ignored" for IPv6 addresses, until this support is implemented.
