### ISSUE TITLE
.local cannot be resolved

### ISSUE THREAD

**Issue by Nailik** [home-assistant/plugin-dns#89]
Hi,

i have version (ha dns info) 2022.04.1 with homeAssistant 2022.5.0 and since today i cannot anymore resolve Adresses with ".local"
My setup is a fritzBox that has a Rpi with PiHole as Network DNS.

For example tv.local or www.tv.local cannot be resolved, there is no request being made to the PiHole.
When i change to tv.de or www.tv.de it works, from my other devices in the Network there is no issue calling tv.local.

ha resolution info shows no issues.

**Comment by jsbrich** [comment]
I am seeing the same thing with an AdGuardHome LXC and updating to 2022.5.0 today

**Comment by jsbrich** [comment]
Looks like HA updated it's forwarders in the DNS to follow the rules and not forward .local as that is reserved for mDNS and llmnr.  So if you use something besides .local, it should work again.  If we are all following the rules, technically, .home.arpa is what you should use according to RFC 8375

**Comment by Nailik** [comment]
Okay so i will switch to .home.arpa thank you

**Comment by mdegat01** [comment]
Yea what jsbrich said is correct. Resolving this as this is how its supposed to be working.

**Comment by NODeeJay** [comment]
There is another solution that allows coexistence of mDNS and a FQDN that ends in .local, e.g.: mydomain.local
Please see: https://community.home-assistant.io/t/local-dns/178108/144
